### ISSUE TITLE
🙋 Blobs API  使用要求解惑

### ISSUE THREAD

**Issue by an0202** [eryajf/gitlabCodeSearch#1]
首先感谢您的这个工具，对我们很有帮助，也收到了很多启发。
我发现工具检索内容时使用的是[blobs scope api](https://archives.docs.gitlab.com/14.2/ee/api/search.html#scope-blobs-premium-2)；针对这个api，按照官方文档，理论上只有[Gitlab PREMIUM](https://about.gitlab.com/pricing/)版本才可以使用。
可实际上我们使用的是Gitlab CE(14.2.x 比较老)，也没有安装ES，按理说是不能使用的，但实际使用发现确实可以正常工作，所以有些疑惑，希望听一下您关于这个问题的想法。

**Comment by eryajf** [comment]
似乎的确如此，我在编写代码的时候也注意到了这个问题，但后来发现在13.x, 14.x,15.x上边都是能够正常工作的。

具体原因是什么，这个我也说不好。

**Comment by an0202** [comment]
谢谢，我会持续关注下。
